steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/job-tracker-neon:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/job-tracker-neon:latest',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'gcr.io/$PROJECT_ID/job-tracker-neon:$COMMIT_SHA'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'gcr.io/$PROJECT_ID/job-tracker-neon:latest'
    ]

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'job-tracker-neon',
      '--image', 'gcr.io/$PROJECT_ID/job-tracker-neon:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8001',
      '--set-env-vars', 'NODE_ENV=production'
    ]

images:
  - 'gcr.io/$PROJECT_ID/job-tracker-neon:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/job-tracker-neon:latest'

options:
  logging: CLOUD_LOGGING_ONLY